server:
  port: 9002
  tomcat:
    access-log-enabled: true


auto:
  create:
    topics:
      enable: 'true'
topic:
  name:
    producer: application.mails

spring:
  application:
    useOTP: true
    otpProd: true
    otpTestMail: ckibet@emtechhouse.co.ke
    logs:
      user: C:\Users\joshu\Emtech\microservice\EMT_MULTITENANT_SACCO\Server\api_gateway_service\src\main\resources\Userlogs/user.log
    name: API-GATEWAY
    enableEmail: true
    client:
      origin_local_server: http://localhost/
      origin_local: http://localhost:4200/

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        show_sql: true

  datasource:
    url: jdbc:mariadb://localhost:3306/ecletics_io
    username: root
    password:
    driverClassName: org.mariadb.jdbc.Driver

  #EMAIL CONFIGURATIONS
  mail:
    protocol: smtps
    host: mail.talktous@eclectics.io
    port: 465
    username: talktous@eclectics.io
    password: Pass123$$
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: mail.talktous@eclectics.io
  organisation:
    emailRegards: Regards Eclectics 3.0
    emailMessage: Find the attached information from our partnership
    emailOrganizationName: Eclectics International

    image_banner:

    emailRemarks: Thank You.
    emailOrganizationLocation: Utumishi House
    emailOrganizationPhone: +255 7** *** ***
    emailOrganizationWebsite: talktous@eclectics.io
    emailOrganizationMail: talktous@eclectics.ioe
    emailOrganizationAddress:  P.O Box 00, 0000 Nairobi
    from_mail: talktous@eclectics.io

    company_logo_path:

    emailSalutation: Dear Sir/Madam,

eureka:
  client:
    region: default
    enabled: true
    register-with-eureka: true
    fetch-registry: true
    registryFetchIntervalSeconds: 5
    service-url:
      defaultZone: http://localhost:9001/eureka

  instance:
    hostname: localhost
    nonSecurePort: 80
    leaseRenewalIntervalInSeconds: 5

users:
  app:
    jwtSecret: /buCOEjS/+H7ZwekxyLKLdDeegHUGEytjxuivosdrzjRG4g4E+kA3uXO5lvGBVsl2NwqsgiGUUI5bjgY/6WG/VSIIG+22b1Rvdb59BY0YRod6Dnjnp0REsPn//hshs6ucnOVCBRp0lbVb1kP+EDOM7W7N72/+t+R1d8JQ4pjisoJZI4e0MV3PlZtzXKI0SY2EQUtI
    jwtExpirationMs: 43200000

organisation:
  email: talktous@eclectics.io
  superUserEmail: talktous@eclectics.io
  superUserFirstName: Superuser
  superUserLastName: Admin
  superUserUserName: Superuser
  superUserPhone: +254202710274
  superUserPassword: SuPassCode12


  zuul:
    host:
      connect-timeout-millis: 2000
      socket-timeout-millis: 5000

    routes:
      health-facility-service:
        sensitiveHeaders:
        url: http://localhost:9003

      clinical-officers-service:
        sensitiveHeaders:
        url: http://localhost:9004

      member-data-service:
        sensitiveHeaders:
        url: http://localhost:9005

      feedback-service:
        sensitiveHeaders:
        url: http://localhost:9006



ribbon:
  ConnectTimeout: 60000
  ReadTimeout: 600000
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false


management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS